# Generated by Django 5.2.16 on 2026-07-20 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Biriktirilgan sana')),
                ('current_day', models.IntegerField(default=0, verbose_name='Hozirgi kun')),
                ('status', models.CharField(choices=[('in_progress', 'Davom etmoqda'), ('completed', 'Tugallangan'), ('paused', "To'xtatilgan"), ('not_started', 'Boshlanmagan')], default='not_started', max_length=20, verbose_name='Holat')),
                ('pre_assessment_score', models.IntegerField(blank=True, null=True, verbose_name='Kirish testi natijasi')),
                ('pre_assessment_passed', models.BooleanField(default=False, verbose_name="Kirish testidan o'tdimi")),
                ('skipped_days', models.IntegerField(default=0, verbose_name="O'tkazilgan kunlar")),
                ('certified_at', models.DateTimeField(blank=True, null=True, verbose_name='Sertifikat sanasi')),
                ('certificate_url', models.CharField(blank=True, max_length=500, verbose_name='Sertifikat URL')),
                ('recertification_due', models.DateTimeField(blank=True, null=True, verbose_name="Qayta o'qitish muddati")),
                ('position_version', models.IntegerField(default=1, verbose_name='Lavozim versiyasi')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_positions', to=settings.AUTH_USER_MODEL, verbose_name='Mentor')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_positions', to='departments.position', verbose_name='Lavozim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_positions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi lavozimi',
                'verbose_name_plural': 'Foydalanuvchi lavozimlari',
                'unique_together': {('user', 'position')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan sana')),
                ('quiz_score_percent', models.IntegerField(blank=True, null=True, verbose_name='Test natijasi (%)')),
                ('attempts_count', models.IntegerField(default=0, verbose_name='Urinishlar soni')),
                ('feedback_rating', models.IntegerField(blank=True, null=True, verbose_name='Baho (1-5)')),
                ('feedback_comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_skipped', models.BooleanField(default=False, verbose_name="O'tkazib yuborilganmi")),
                ('route_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='content.routeday', verbose_name='Kun')),
                ('user_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='progress.userposition', verbose_name='Foydalanuvchi lavozimi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi progressi',
                'verbose_name_plural': 'Foydalanuvchi progresslari',
                'unique_together': {('user_position', 'route_day')},
            },
        ),
    ]
