# Generated by Django 5.2.16 on 2026-07-20 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_text', models.TextField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_notes', to=settings.AUTH_USER_MODEL, verbose_name='Mentor')),
                ('user_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_notes', to='progress.userposition', verbose_name='Xodim/Lavozim')),
            ],
            options={
                'verbose_name': 'Mentor izohi',
                'verbose_name_plural': 'Mentor izohlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
