# Generated by Django 5.2.16 on 2026-07-20 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_pre_assessment', models.BooleanField(default=False, verbose_name='Kirish testi savolimi')),
                ('question_type', models.CharField(choices=[('single_choice', 'Bir tanlovli'), ('multi_choice', "Ko'p tanlovli"), ('scenario_choice', 'Stsenariy')], max_length=20, verbose_name='Savol turi')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('media_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Media URL')),
                ('explanation_text', models.TextField(blank=True, verbose_name='Tushuntirish')),
                ('points', models.IntegerField(default=1, verbose_name='Ball')),
                ('version', models.IntegerField(default=1, verbose_name='Versiya')),
                ('route_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.routeday', verbose_name='Kun')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=500, verbose_name='Javob varianti')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'rimi")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='testing.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
    ]
