# Generated by Django 5.2.16 on 2026-07-20 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Bo'lim nomi")),
                ('theme_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Rang (hex)')),
                ('icon_set', models.CharField(default='default', max_length=100, verbose_name="Ikonlar to'plami")),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Lavozim nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='medium', max_length=10, verbose_name='Qiyinlik darajasi')),
                ('total_days', models.IntegerField(default=0, verbose_name='Jami kunlar')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Holat')),
                ('recertification_months', models.IntegerField(blank=True, null=True, verbose_name="Qayta o'qitish (oy)")),
                ('has_pre_assessment', models.BooleanField(default=False, verbose_name='Kirish testi bormi')),
                ('pre_assessment_threshold', models.IntegerField(blank=True, null=True, verbose_name="Kirish testi o'tish foizi")),
                ('pre_assessment_skip_days', models.IntegerField(blank=True, null=True, verbose_name="O'tkazib yuboriladigan kunlar")),
                ('version', models.IntegerField(default=1, verbose_name='Versiya')),
                ('effective_from', models.DateTimeField(auto_now_add=True, verbose_name='Kuchga kirish sanasi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='departments.department', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
            },
        ),
    ]
