# Generated by Django 5.2.16 on 2026-07-20 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='media_library/', verbose_name='Fayl')),
                ('file_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video'), ('audio', 'Audio')], max_length=10, verbose_name='Fayl turi')),
                ('tags', models.TextField(blank=True, verbose_name='Teglar')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan')),
            ],
            options={
                'verbose_name': 'Media kutubxona',
                'verbose_name_plural': 'Media kutubxona',
            },
        ),
        migrations.CreateModel(
            name='RouteDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField(verbose_name='Kun raqami')),
                ('title', models.CharField(max_length=255, verbose_name='Kun sarlavhasi')),
                ('node_image_url', models.CharField(blank=True, max_length=500, verbose_name='Tugun rasmi')),
                ('unlock_rule', models.CharField(choices=[('previous_completed', 'Oldingi kun tugallansa'), ('date_based', "Ma'lum sanada ochiladi"), ('manual', "Admin qo'lda ochadi")], default='previous_completed', max_length=20, verbose_name='Ochilish qoidasi')),
                ('pass_threshold_percent', models.IntegerField(default=80, verbose_name="O'tish foizi")),
                ('is_skippable', models.BooleanField(default=False, verbose_name="O'tkazib yuborish mumkinmi")),
                ('version', models.IntegerField(default=1, verbose_name='Versiya')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_days', to='departments.position', verbose_name='Lavozim')),
            ],
            options={
                'verbose_name': 'Route Map kuni',
                'verbose_name_plural': 'Route Map kunlari',
                'ordering': ['day_number'],
                'unique_together': {('position', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(verbose_name='Tartib')),
                ('block_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Matn'), ('image_text', 'Rasm + Matn'), ('scenario', 'Stsenariy')], max_length=20, verbose_name='Blok turi')),
                ('media_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Media URL')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Davomiylik (soniya)')),
                ('version', models.IntegerField(default=1, verbose_name='Versiya')),
                ('route_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='content.routeday', verbose_name='Kun')),
            ],
            options={
                'verbose_name': 'Kontent blok',
                'verbose_name_plural': 'Kontent bloklar',
                'ordering': ['order_index'],
            },
        ),
    ]
