# Generated by Django 5.2.16 on 2026-07-20 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGamification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xp_total', models.IntegerField(default=0, verbose_name='Jami XP')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Hozirgi streak')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='Eng uzun streak')),
                ('level', models.IntegerField(default=1, verbose_name='Daraja')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Oxirgi faoliyat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "O'yin ko'rsatkichi",
                'verbose_name_plural': "O'yin ko'rsatkichlari",
            },
        ),
    ]
