# Generated by Django 5.2.16 on 2026-07-20 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('daily_reminder', 'Kunlik eslatma'), ('streak_warning', 'Streak ogohlantirishi'), ('quiz_result', 'Test natijasi'), ('recertification_due', "Qayta o'qitish eslatmasi"), ('mentor_assigned', 'Mentor biriktirildi')], max_length=30, verbose_name='Turi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('web_push', 'Web Push'), ('email', 'Email')], max_length=15, verbose_name='Kanal')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan sana')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilganmi")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-sent_at'],
            },
        ),
    ]
